<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Eddy App</title>
		<meta name="description" content="" />
		
		<link href="//netdna.bootstrapcdn.com/bootswatch/2.1.0/slate/bootstrap.min.css" rel="stylesheet" />
		<style>
			body {
				padding-top: 40px;
			}
		</style>
		
		<!-- Le fav and touch icons -->
		<? /*
		<link rel="shortcut icon" href="images/favicon.ico">
		<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
		<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
		 */ ?>
		 
		<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.0/js/bootstrap.min.js"></script>
		
		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		
	</head>

	<body>
		<nav class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="brand" href="<?= SITE_ROOT ?>/">Eddy App</a>
					<ul class="nav">
						<li class="active"><a href="<?= SITE_ROOT ?>/">Home</a></li>
					</ul>
				</div>
			</div>
		</nav>

		<div class="container">
			<div class="content">
				<?php EddyView::load(); ?>
			</div>
			
			<footer></footer>
		</div>
	</body>
</html>